### ISSUE TITLE
How to load SQuAD as pred parts ?

### ISSUE THREAD

**Issue by Arjunsankarlal** [bernhard2202/rankqa#1]
In `rankqa/run.py` line 42, for loading the train files, the below code has been used.

`train_filesSQ = [os.path.join('features',
                              'SQuAD-v1.1-train-default-pipeline.preds-part-{}'.format(i)) for i in range(88)]`

But I wondering, where to download SQuAD in this format, I able to download a single train JSON file for SQuAD.

Kindly guide me how to do it. Thanks.

**Comment by bernhard2202** [comment]
Hi, 
we provide precomputed and aggregated answer candidates for all questions in the SQuAD dataset so you don't have to run the full QA pipeline every time.
You can find more information including a download link for the files you are missing here: https://github.com/bernhard2202/rankqa/tree/master/rankqa

**Comment by Arjunsankarlal** [comment]
Thanks for quick reply, I really missed it in the README.md, Now I am looking to use this trained model that we get in the `out` directory, to make it work for my data. Given a paragraph and question, I am looking to take the answer span for it, as DrQA does. Can we achieve it with the current repo?

**Comment by bernhard2202** [comment]
Hi, if your data is one of the datasets used in the paper (SQuAD, WikiMovies, WebQuestions, TREC) you can download the precomputed features for those datasets and use the model as-is. If you want to use another dataset you will need to generate features. Unfortunately, the code to generate features for the DrQA pipeline is not published yet, but I will provide it in time before the ACL Conference. If you want to use the BERT-QA pipeline you can use the code provided here: https://github.com/bernhard2202/rankqa/tree/master/bertqa

**Comment by bernhard2202** [comment]
Hi, just wanted to say that I haven't managed to clean the code for feature generation and publish it, yet. In case you are interested please feel free to write me a mail and I will send it to you. 

Best, 
Bernhard
